#!/bin/bash

# install R
apk update && apk add R R-dev R-doc build-base

# install package
R -e "install.packages('jsonlite', repos = 'http://cran.rstudio.com/')"

# run R script
chmod +x script.R # turn executable
echo "$@" > input.json # set input
./script.R # run script

